// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCre4ihjxWFoyhFlXUeRwc6CbFegrAcf8E',
    appId: '1:650937520834:web:3d1468ef3fe09e8022a15b',
    messagingSenderId: '650937520834',
    projectId: 'tubes-b91ea',
    authDomain: 'tubes-b91ea.firebaseapp.com',
    storageBucket: 'tubes-b91ea.firebasestorage.app',
    measurementId: 'G-FV64KNBTPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwpYtYIQZttGkZ1muOr7WaRjF1hBdBOYE',
    appId: '1:650937520834:android:618964cae3ef740e22a15b',
    messagingSenderId: '650937520834',
    projectId: 'tubes-b91ea',
    storageBucket: 'tubes-b91ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6obQW3sPRLvYnP2E45Cg-FC1bDAZHt0',
    appId: '1:650937520834:ios:58bb6e70920221f922a15b',
    messagingSenderId: '650937520834',
    projectId: 'tubes-b91ea',
    storageBucket: 'tubes-b91ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw6obQW3sPRLvYnP2E45Cg-FC1bDAZHt0',
    appId: '1:650937520834:ios:58bb6e70920221f922a15b',
    messagingSenderId: '650937520834',
    projectId: 'tubes-b91ea',
    storageBucket: 'tubes-b91ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTubes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCre4ihjxWFoyhFlXUeRwc6CbFegrAcf8E',
    appId: '1:650937520834:web:8543c5f6db4161e022a15b',
    messagingSenderId: '650937520834',
    projectId: 'tubes-b91ea',
    authDomain: 'tubes-b91ea.firebaseapp.com',
    storageBucket: 'tubes-b91ea.firebasestorage.app',
    measurementId: 'G-KVRT29QHML',
  );
}
